### ISSUE TITLE
code to download vim-plug appears to be missing

### ISSUE THREAD

**Issue by markstos** [olivier-o/ansible-role-vim-plug#3]
The default variables like this one are declared in the project, but then never referenced:

`vim_plug_dest`

The tasks omit the step of downloading `vim-plug`, which would be the step that uses the variables:

https://github.com/olivier-o/ansible-role-vim-plug/blob/master/tasks/main.yml

**Comment by markstos** [comment]
Here's an example block that works for NeoVim, but doesn't use variables:

```yaml
    # Install vim-plug for Neovim (as local user, not root)
    - block:
        - name: Make "~/.local/share/nvim/site/autoload" directory
          file: path="~/.local/share/nvim/site/autoload" state=directory

        - name: Install vim-plug
          get_url:
            url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
            dest: "~/.local/share/nvim/site/autoload/plug.vim"
            force: yes
```
